### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by haithanhnguyen** [timokousa/hod#1]
Hi,

Thanks for your applications. It's very useful for me.

But, I cannot install, occur some error when building this app.

/var/www/video/hod-master/tools/segmenter.c:324: undefined reference to `AES_set_encrypt_key'
/var/www/video/hod-master/tools/segmenter.c:327: undefined reference to`RAND_bytes'
/var/www/video/hod-master/tools/segmenter.c:328: undefined reference to `ERR_get_error'
/var/www/video/hod-master/tools/segmenter.c:328: undefined reference to`ERR_error_string'
/var/www/video/hod-master/tools/segmenter.c:522: undefined reference to `AES_cbc_encrypt'
/var/www/video/hod-master/tools/segmenter.c:580: undefined reference to`RAND_bytes'
/var/www/video/hod-master/tools/segmenter.c:582: undefined reference to `ERR_get_error'
/var/www/video/hod-master/tools/segmenter.c:582: undefined reference to`ERR_error_string'
/var/www/video/hod-master/tools/segmenter.c:633: undefined reference to `AES_cbc_encrypt'
/var/www/video/hod-master/tools/segmenter.c:694: undefined reference to`AES_cbc_encrypt'
/var/www/video/hod-master/tools/segmenter.c:742: undefined reference to `AES_cbc_encrypt'
collect2: error: ld returned 1 exit status
make: **\* [segmenter] Error 1

Please help me how to fix above error. Thanks very much!

**Comment by timokousa** [comment]
This should be now fixed by commit 6d6f882b1bf9f6495308d9a2db16c5c7263d835d
